"""restructure users table

Revision ID: 41ed24e70a50
Revises: 80d213134faa
Create Date: 2026-07-11 13:07:00.070011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ed24e70a50'
down_revision: Union[str, Sequence[str], None] = '80d213134faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lists_owner_id_fkey'), 'lists', type_='foreignkey')
    op.drop_constraint(op.f('todos_owner_id_fkey'), 'todos', type_='foreignkey')

    op.execute('ALTER TABLE users ALTER COLUMN id DROP DEFAULT')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::text::uuid')
    op.alter_column('lists', 'owner_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='owner_id::text::uuid')
    op.alter_column('todos', 'owner_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='owner_id::text::uuid')

    op.create_foreign_key(op.f('lists_owner_id_fkey'), 'lists', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('todos_owner_id_fkey'), 'todos', 'users', ['owner_id'], ['id'])

    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'name')

    op.drop_constraint(op.f('lists_owner_id_fkey'), 'lists', type_='foreignkey')
    op.drop_constraint(op.f('todos_owner_id_fkey'), 'todos', type_='foreignkey')

    op.alter_column('todos', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               postgresql_using=None)
    op.alter_column('lists', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               postgresql_using=None)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using=None)

    op.create_foreign_key(op.f('lists_owner_id_fkey'), 'lists', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('todos_owner_id_fkey'), 'todos', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
