"""make todo list_id required with cascade delete

Revision ID: cf98bac75344
Revises: 41ed24e70a50
Create Date: 2026-07-11 13:20:09.341680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf98bac75344'
down_revision: Union[str, Sequence[str], None] = '41ed24e70a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('todos_list_id_fkey'), 'todos', type_='foreignkey')
    op.create_foreign_key(
        op.f('todos_list_id_fkey'), 'todos', 'lists', ['list_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('todos_list_id_fkey'), 'todos', type_='foreignkey')
    op.create_foreign_key(op.f('todos_list_id_fkey'), 'todos', 'lists', ['list_id'], ['id'])
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
